### ISSUE TITLE
Not able to find nightwatch.

### ISSUE THREAD

**Issue by michaelerobertsjr** [tatsuyafw/gulp-nightwatch#23]
Several of us in our office did an install and it pulled in your latest version 2.3, which resulted in an error:

module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp-nightwatch'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/hanam/Sites/optimize-max-cms/gulpfile.js:9:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Once we rolled back the version to 2.2 in package.json it works fine...

**Comment by tatsuyafw** [comment]
Hi @michaelerobertsjr .

Oh, sorry... It's my release mistake.
I'll fix this problem within a few hours. Please use `v0.2.2` for now.

**Comment by tatsuyafw** [comment]
@michaelerobertsjr 

I've released `v0.2.4`. I think the new version fixes this problem.
Could you use `v0.2.4` ?

**Comment by louiscbotha** [comment]
Had the same problem on v0.2.3. v0.2.4 seems to work.

**Comment by tatsuyafw** [comment]
@louiscbotha 

Thanks.
This issue seems to have fixed. I closed.
