### ISSUE TITLE
v0.2.8 published tarball is missing index.js

### ISSUE THREAD

**Issue by rike422** [tatsuyafw/gulp-nightwatch#35]
```
> require("gulp-nightwatch")
Error: Cannot find module 'gulp-nightwatch'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
```

```
[17:23:33]() tree -L 1 gulp-nightwatch                                  
gulp-nightwatch
├── LICENSE
├── README.md
├── lib
├── node_modules
└── package.json
```

issues looks the same to me #29

**Comment by jackiemcghee** [comment]
Confirmed, here. No `index.js`.

**Comment by tatsuyafw** [comment]
Oh, sorry..

I will fix this issue. Please wait a few hours.

**Comment by tatsuyafw** [comment]
Hi @rike422 , @jackiemcghee .

I've released v0.2.9, and confirmed the new version includes `index.js`.
Please use v0.2.9 instead of v0.2.8.

**Comment by FranzPoize** [comment]
Thx :+1:

**Comment by jackiemcghee** [comment]
Thanks, @tatsuyafw

**Comment by rike422** [comment]
thx!
